title: Emma Bennett
description: CS and ECE at Duke. Software, research, and machine learning.
url: "https://eb45.github.io"
baseurl: ""

exclude:
  - ".jekyll-cache"
  - ".jekyll-metadata"
  - ".sass-cache"
  - ".idea"
  - ".github"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
  - "README.md"
  - "node_modules"
